### ISSUE TITLE
fix: UINT comparison not working

### ISSUE THREAD

**Issue by mmackz** [rabbitholegg/boost-protocol#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

alpha.13

### Current Behavior

When comparing UINT, the filterData has to be in hexadecimal form, and the fieldValue can be a bigInt.

For example, if we wanted to match a tokenId with the value of 3n, it would compare "0x03" with 3n which resolves to false.

### Expected Behavior

Normalize the hexadecimal and field values so they can be compared properly.

### Steps To Reproduce

Input a value as a hexadecimal string and have it compared to a field value that is a bigint.

![CleanShot 2024-10-01 at 10 49 42@2x](https://github.com/user-attachments/assets/5eb8881a-0ecb-498b-a9aa-823a6ab43ac7)

**Comment by sammccord** [comment]
i think we should run everything through https://viem.sh/docs/utilities/fromHex based on the primitive type before comparing
