### ISSUE TITLE
feat(docs): document how the `params?.chainId`  and `assertValidAddressByChainId` work on registry/core

### ISSUE THREAD

**Issue by sammccord** [rabbitholegg/boost-protocol#163]
### Description

@benjaminykim asked about managing the sdk's chain id + protocol addresses on the frontend. In the docs repo, document how we target core/registry addresses based on how `assertValidAddressByChainId` falls through cases

### Suggested Solution

In the docs repo, in the quick start snippets, add a block showing how you can supply a `chainId` in params, then add comments around it explaining how registry and core will attempt to use their addresses for the given chain id, then fall back to address by connected account chain id, then the default chain

**Comment by mmackz** [comment]
https://github.com/rabbitholegg/docs/pull/17
